"""
Multi-Agent Document Research & Analytics System
=================================================
A state-of-the-art Multi-Agent system built with Python 3.10+, LangGraph 0.2+,
ChatGroq (llama3-70b/llama-3.3-70b), Supabase pgvector (RAG), HuggingFace Embeddings,
and Tavily Web Search fallback.

Architecture Flow:
Input Topic -> Orchestrator Node -> Retrieval Agent Node (Supabase pgvector)
             -> [Conditional Edge: Context Density Evaluation]
                  ├─► Sparse/Insufficient -> Web Search Fallback Node (Tavily) -> Synthesis Agent
                  └─► Sufficient          ----------------------------------------> Synthesis Agent
             -> Output: Executive Markdown Report
"""

import os
import json
from typing import List, Dict, Any, Optional, TypedDict
from dotenv import load_dotenv
from pydantic import BaseModel, Field

# Base LangChain & LangGraph Imports
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, START, END

# LLM, Embedding, VectorStore & Web Search Imports (Safe Imports)
try:
    from langchain_groq import ChatGroq
except ImportError:
    ChatGroq = None

try:
    from langchain_huggingface import HuggingFaceEmbeddings
except ImportError:
    HuggingFaceEmbeddings = None

try:
    from supabase import create_client, Client
except ImportError:
    create_client, Client = None, None

try:
    from langchain_community.vectorstores import SupabaseVectorStore
except ImportError:
    SupabaseVectorStore = None

try:
    from langchain_community.tools import TavilySearchResults
except ImportError:
    TavilySearchResults = None


# Load Environment Variables from .env file (used only for standalone CLI runs)
load_dotenv()


# ============================================================================
# 1. STATE DEFINITION (TypedDict & Pydantic V2)
# ============================================================================
class ResearchState(TypedDict):
    """
    Type-safe global state maintained throughout the LangGraph workflow.
    """
    topic: str                        # Input user research topic
    search_queries: List[str]         # Sub-queries generated by Orchestrator
    retrieved_docs: List[Document]    # Dense context retrieved from Supabase RAG
    web_search_results: List[Dict[str, Any]] # Fallback live context from Tavily
    need_web_search: bool             # Flag indicating if vector context was sparse
    final_report: str                 # Formatted Markdown report string


class SubQueryOutput(BaseModel):
    """Pydantic model for type-safe sub-query generation by Orchestrator."""
    queries: List[str] = Field(
        description="List of 3 to 5 focused sub-queries for targeted document retrieval."
    )


# ============================================================================
# HELPER / LLM INITIALIZERS WITH CRASH PROTECTION
# Keys are passed as parameters (not read from module-level globals) so that
# per-request key injection from the frontend actually takes effect.
# ============================================================================
def get_groq_llm(groq_api_key: str = "", temperature: float = 0.2) -> Optional[Any]:
    """Instantiates ChatGroq client with error handling for missing API keys or imports."""
    # Fall back to env var if no key passed explicitly
    key = groq_api_key or os.getenv("GROQ_API_KEY", "")
    if ChatGroq is None or not key or key.startswith("your_"):
        return None
    try:
        return ChatGroq(
            model_name="llama-3.3-70b-versatile",
            groq_api_key=key,
            temperature=temperature
        )
    except Exception as e:
        print(f"[Warning] Failed to initialize ChatGroq client: {e}")
        return None


_EMBEDDINGS_CACHE: Optional[Any] = None


def get_embeddings() -> Optional[Any]:
    """
    Instantiates (once) and caches the HuggingFace local embedding model
    (all-MiniLM-L6-v2). Loading this model spins up a torch/sentence-transformers
    session, which is expensive — reusing a single cached instance for the life
    of the process avoids reloading it on every incoming request.
    """
    global _EMBEDDINGS_CACHE
    if _EMBEDDINGS_CACHE is not None:
        return _EMBEDDINGS_CACHE
    if HuggingFaceEmbeddings is None:
        return None
    try:
        _EMBEDDINGS_CACHE = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
        return _EMBEDDINGS_CACHE
    except Exception as e:
        print(f"[Warning] Failed to initialize HuggingFaceEmbeddings: {e}")
        return None


def get_supabase_vectorstore(supabase_url: str = "", supabase_service_key: str = "") -> Optional[Any]:
    """Instantiates Supabase pgvector store client safely."""
    url = supabase_url or os.getenv("SUPABASE_URL", "")
    key = supabase_service_key or os.getenv("SUPABASE_SERVICE_KEY", "")
    if SupabaseVectorStore is None or create_client is None or not url or not key or url.startswith("your_"):
        return None

    try:
        embeddings = get_embeddings()
        if not embeddings:
            return None
        client: Client = create_client(url, key)
        vector_store = SupabaseVectorStore(
            client=client,
            embedding=embeddings,
            table_name="documents",
            query_name="match_documents"
        )
        return vector_store
    except Exception as e:
        print(f"[Warning] Supabase vector store connection failed: {e}")
        return None


# ============================================================================
# 2. ORCHESTRATOR NODE
# ============================================================================
def orchestrator_node(state: ResearchState) -> Dict[str, Any]:
    """
    Takes the broad research topic and generates 3 to 5 targeted sub-queries
    using ChatGroq to optimize vector document retrieval.
    """
    topic = state["topic"]
    print(f"\n[Orchestrator Node] Processing Topic: '{topic}'")
    
    llm = get_groq_llm(temperature=0.3)
    
    if llm:
        try:
            structured_llm = llm.with_structured_output(SubQueryOutput)
            prompt = ChatPromptTemplate.from_messages([
                ("system", "You are an expert Principal AI Research Lead. "
                           "Break down the user's research topic into 3 to 5 highly specific, "
                           "technical sub-queries optimized for semantic document retrieval."),
                ("human", "Research Topic: {topic}")
            ])
            formatted_prompt = prompt.format_messages(topic=topic)
            response: SubQueryOutput = structured_llm.invoke(formatted_prompt)
            queries = response.queries
        except Exception as e:
            print(f"[Orchestrator Node] Groq LLM invocation failed ({e}). Falling back to rule-based queries.")
            queries = [
                f"{topic} core architecture and technical specifications",
                f"{topic} implementation details and key components",
                f"{topic} performance, benchmarks, and comparative analysis"
            ]
    else:
        print("[Orchestrator Node] No Groq API Key found. Using default sub-queries for offline execution.")
        queries = [
            f"{topic} core architecture and technical specifications",
            f"{topic} implementation details and key components",
            f"{topic} performance, benchmarks, and comparative analysis"
        ]
        
    print(f"[Orchestrator Node] Generated Sub-Queries:\n  - " + "\n  - ".join(queries))
    return {"search_queries": queries}


# ============================================================================
# 3. RETRIEVAL AGENT NODE (Supabase RAG)
# ============================================================================
def retrieval_node(state: ResearchState) -> Dict[str, Any]:
    """
    Queries Supabase pgvector store using HuggingFace dense embeddings.
    Evaluates retrieved document sufficiency against threshold.
    """
    queries = state.get("search_queries", [state["topic"]])
    print(f"\n[Retrieval Agent Node] Querying Supabase pgvector store with {len(queries)} sub-queries...")
    
    vector_store = get_supabase_vectorstore()
    retrieved_docs: List[Document] = []
    seen_contents = set()
    
    if vector_store:
        try:
            for query in queries:
                # Perform cosine similarity search for each sub-query
                docs = vector_store.similarity_search(query, k=2)
                for doc in docs:
                    if doc.page_content not in seen_contents:
                        seen_contents.add(doc.page_content)
                        retrieved_docs.append(doc)
            print(f"[Retrieval Agent Node] Successfully retrieved {len(retrieved_docs)} unique documents from Supabase.")
        except Exception as e:
            print(f"[Retrieval Agent Node] Supabase RAG query error: {e}")
    else:
        print("[Retrieval Agent Node] Supabase vector store not configured or unavailable. Operating in local mode.")
    
    # Sufficiency check: compare retrieved doc count with threshold
    need_web_search = len(retrieved_docs) < DOC_RELEVANCE_THRESHOLD
    
    if need_web_search:
        print(f"[Retrieval Agent Node] Context Sparse! Retrieved {len(retrieved_docs)} docs (Threshold: {DOC_RELEVANCE_THRESHOLD}). Flagging for Web Search Fallback.")
    else:
        print(f"[Retrieval Agent Node] Context Sufficient! Retrieved {len(retrieved_docs)} docs.")
        
    return {
        "retrieved_docs": retrieved_docs,
        "need_web_search": need_web_search
    }


# ============================================================================
# 4. CONDITIONAL EDGE ROUTER
# ============================================================================
def decide_fallback(state: ResearchState) -> str:
    """
    Conditional Edge: Routes execution path based on need_web_search flag.
    Returns destination node name: 'web_search' or 'synthesis'.
    """
    if state.get("need_web_search", False):
        print("\n[Conditional Router] Routing -> Web Search Fallback Node")
        return "web_search"
    else:
        print("\n[Conditional Router] Routing -> Synthesis Agent Node")
        return "synthesis"


# ============================================================================
# 5. WEB SEARCH FALLBACK NODE (Tavily Search API)
# ============================================================================
def web_search_node(state: ResearchState) -> Dict[str, Any]:
    """
    Executes live web search using Tavily API if Supabase document retrieval
    was sparse or insufficient.
    """
    queries = state.get("search_queries", [state["topic"]])
    print(f"\n[Web Search Fallback Node] Executing live web search using Tavily for queries...")
    
    web_results: List[Dict[str, Any]] = []
    
    if TavilySearchResults is not None and TAVILY_API_KEY and not TAVILY_API_KEY.startswith("your_"):
        try:
            tavily = TavilySearchResults(tavily_api_key=TAVILY_API_KEY, max_results=2)
            for q in queries[:2]: # Search top 2 queries to remain within rate limits
                results = tavily.invoke({"query": q})
                if isinstance(results, list):
                    web_results.extend(results)
            print(f"[Web Search Fallback Node] Fetched {len(web_results)} live search snippets from Tavily.")
        except Exception as e:
            print(f"[Web Search Fallback Node] Tavily Search API error ({e}). Using fallback web mock data.")
            web_results = _get_mock_web_results(state["topic"])
    else:
        print("[Web Search Fallback Node] Tavily API key missing or unconfigured. Using structured mock web search results.")
        web_results = _get_mock_web_results(state["topic"])

    return {"web_search_results": web_results}


def _get_mock_web_results(topic: str) -> List[Dict[str, Any]]:
    """Returns clean mock web results when Tavily key is absent."""
    return [
        {
            "title": f"Latest Developments in {topic}",
            "snippet": f"Recent industry benchmarks show significant performance gains when implementing modern {topic} architectures using modular state management.",
            "url": f"https://example.com/research/{topic.lower().replace(' ', '-')}"
        },
        {
            "title": f"Technical Deep-Dive: {topic} Systems",
            "snippet": f"Best practices for {topic} include hybrid dense retrieval, fallback search routing, and low-latency LLM synthesis pipelines.",
            "url": f"https://example.com/docs/{topic.lower().replace(' ', '-')}"
        }
    ]


# ============================================================================
# 6. SYNTHESIS AGENT NODE
# ============================================================================
def synthesis_node(state: ResearchState) -> Dict[str, Any]:
    """
    Aggregates RAG context and web search results, using ChatGroq to generate
    an executive-ready, structured Markdown report.
    """
    topic = state["topic"]
    docs = state.get("retrieved_docs", [])
    web_results = state.get("web_search_results", [])
    
    print(f"\n[Synthesis Agent Node] Compiling final report for topic: '{topic}'...")
    
    # Format vector context
    doc_context_str = ""
    if docs:
        for i, doc in enumerate(docs, 1):
            source = doc.metadata.get("source", "Supabase Vector Store")
            doc_context_str += f"\n--- Vector Document [{i}] (Source: {source}) ---\n{doc.page_content}\n"
    else:
        doc_context_str = "No dense vector documents were retrieved."
        
    # Format web search context
    web_context_str = ""
    if web_results:
        for i, res in enumerate(web_results, 1):
            title = res.get("title", "Web Result")
            url = res.get("url", "#")
            snippet = res.get("snippet", res.get("content", ""))
            web_context_str += f"\n--- Web Search Result [{i}] ---\nTitle: {title}\nURL: {url}\nSnippet: {snippet}\n"
    else:
        web_context_str = "No web search fallback context was required."

    llm = get_groq_llm(temperature=0.2)
    
    if llm:
        try:
            synthesis_prompt = ChatPromptTemplate.from_messages([
                ("system", """You are a Lead AI Systems Engineer writing an executive technical report.
Synthesize the provided vector database context and web search context into a highly structured, polished Markdown report.

Required Sections:
# Executive Summary
## Key Technical Insights
## Comparative Analysis & Findings
## Source Citations

Ensure tone is professional, technical, authoritative, and concise."""),
                ("human", """Research Topic: {topic}

=== SUPABASE VECTOR DATABASE CONTEXT ===
{vector_context}

=== WEB SEARCH FALLBACK CONTEXT ===
{web_context}
""")
            ])
            messages = synthesis_prompt.format_messages(
                topic=topic,
                vector_context=doc_context_str,
                web_context=web_context_str
            )
            response = llm.invoke(messages)
            report_content = response.content
        except Exception as e:
            print(f"[Synthesis Agent Node] Groq LLM synthesis failed ({e}). Generating template report.")
            report_content = _generate_fallback_report(topic, doc_context_str, web_context_str)
    else:
        print("[Synthesis Agent Node] No Groq API Key found. Generating structured offline report.")
        report_content = _generate_fallback_report(topic, doc_context_str, web_context_str)

    print("[Synthesis Agent Node] Final Markdown Report synthesized successfully.")
    return {"final_report": report_content}


def _generate_fallback_report(topic: str, vector_context: str, web_context: str) -> str:
    """Generates clean structured report when live LLM is offline."""
    return f"""# Executive Summary: {topic}

This comprehensive analytics report evaluates current paradigms and technical implementations regarding **{topic}**. 

## Key Technical Insights
- **Architectural Modularity**: Multi-agent graph orchestrators enable distinct state transitions between vector retrieval and web search fallback mechanisms.
- **Low-Latency Synthesis**: Leveraging optimized inference engines allows rapid processing of retrieved context windows into structured outputs.
- **Context Density Optimization**: Dynamic threshold evaluation prevents hallucinatory outputs by guaranteeing sufficient ground-truth data before report generation.

## Comparative Analysis & Findings
| Metric / Aspect | Vector DB (Supabase pgvector) | Web Search Fallback (Tavily) |
|---|---|---|
| Data Source | Internal Ingested Knowledge Base | Live Web Data |
| Latency | < 50ms (Cosine Similarity Search) | ~300ms (API Round-trip) |
| Primary Role | Domain-Specific Accuracy | Recency & Gap Filling |

## Vector Context Extracted
```
{vector_context.strip()}
```

## Web Search Context Extracted
```
{web_context.strip()}
```

## Source Citations
- Supabase Vector Database Store (`pgvector`)
- Tavily Search Engine / Synthetic Knowledge Base
- Internal LangGraph State Management Pipeline
"""


# ============================================================================
# 7. WORKFLOW GRAPH BUILDER
# ============================================================================
def build_research_graph(
    groq_api_key: str = "",
    tavily_api_key: str = "",
    supabase_url: str = "",
    supabase_service_key: str = "",
    doc_threshold: int = 2,
) -> StateGraph:
    """
    Constructs and compiles the multi-agent state graph using LangGraph.
    API keys are passed as parameters and wired into node closures so that
    each request uses the correct credentials without a global state race condition.
    """
    # Resolve keys: prefer passed args, fall back to env vars
    _groq_key       = groq_api_key       or os.getenv("GROQ_API_KEY", "")
    _tavily_key      = tavily_api_key      or os.getenv("TAVILY_API_KEY", "")
    _supabase_url    = supabase_url        or os.getenv("SUPABASE_URL", "")
    _supabase_svckey = supabase_service_key or os.getenv("SUPABASE_SERVICE_KEY", "")
    _threshold       = doc_threshold

    # ── Node closures that capture resolved keys ───────────────────────────────
    def _orchestrator_node(state: ResearchState) -> Dict[str, Any]:
        topic = state["topic"]
        print(f"\n[Orchestrator Node] Processing Topic: '{topic}'")
        llm = get_groq_llm(groq_api_key=_groq_key, temperature=0.3)
        if llm:
            try:
                structured_llm = llm.with_structured_output(SubQueryOutput)
                prompt = ChatPromptTemplate.from_messages([
                    ("system", "You are an expert Principal AI Research Lead. "
                               "Break down the user's research topic into 3 to 5 highly specific, "
                               "technical sub-queries optimized for semantic document retrieval."),
                    ("human", "Research Topic: {topic}")
                ])
                formatted_prompt = prompt.format_messages(topic=topic)
                response: SubQueryOutput = structured_llm.invoke(formatted_prompt)
                queries = response.queries
            except Exception as e:
                print(f"[Orchestrator Node] Groq LLM invocation failed ({e}). Falling back to rule-based queries.")
                queries = [
                    f"{topic} core architecture and technical specifications",
                    f"{topic} implementation details and key components",
                    f"{topic} performance, benchmarks, and comparative analysis"
                ]
        else:
            print("[Orchestrator Node] No Groq API Key found. Using default sub-queries.")
            queries = [
                f"{topic} core architecture and technical specifications",
                f"{topic} implementation details and key components",
                f"{topic} performance, benchmarks, and comparative analysis"
            ]
        print(f"[Orchestrator Node] Generated Sub-Queries:\n  - " + "\n  - ".join(queries))
        return {"search_queries": queries}

    def _retrieval_node(state: ResearchState) -> Dict[str, Any]:
        queries = state.get("search_queries", [state["topic"]])
        print(f"\n[Retrieval Agent Node] Querying Supabase pgvector with {len(queries)} sub-queries...")
        vector_store = get_supabase_vectorstore(
            supabase_url=_supabase_url,
            supabase_service_key=_supabase_svckey,
        )
        retrieved_docs: List[Document] = []
        seen_contents = set()
        if vector_store:
            try:
                for query in queries:
                    docs = vector_store.similarity_search(query, k=2)
                    for doc in docs:
                        if doc.page_content not in seen_contents:
                            seen_contents.add(doc.page_content)
                            retrieved_docs.append(doc)
                print(f"[Retrieval Agent Node] Retrieved {len(retrieved_docs)} unique documents.")
            except Exception as e:
                print(f"[Retrieval Agent Node] Supabase RAG query error: {e}")
        else:
            print("[Retrieval Agent Node] Supabase not configured. Operating in local mode.")
        need_web_search = len(retrieved_docs) < _threshold
        if need_web_search:
            print(f"[Retrieval Agent Node] Context Sparse! ({len(retrieved_docs)} docs < threshold {_threshold}). Flagging Web Search Fallback.")
        else:
            print(f"[Retrieval Agent Node] Context Sufficient! ({len(retrieved_docs)} docs).")
        return {"retrieved_docs": retrieved_docs, "need_web_search": need_web_search}

    def _web_search_node(state: ResearchState) -> Dict[str, Any]:
        queries = state.get("search_queries", [state["topic"]])
        print(f"\n[Web Search Fallback Node] Executing live Tavily search...")
        web_results: List[Dict[str, Any]] = []
        tavily_key = _tavily_key
        if TavilySearchResults is not None and tavily_key and not tavily_key.startswith("your_"):
            try:
                tavily = TavilySearchResults(tavily_api_key=tavily_key, max_results=2)
                for q in queries[:2]:
                    results = tavily.invoke({"query": q})
                    if isinstance(results, list):
                        web_results.extend(results)
                print(f"[Web Search Fallback Node] Fetched {len(web_results)} snippets from Tavily.")
            except Exception as e:
                print(f"[Web Search Fallback Node] Tavily error ({e}). Using mock data.")
                web_results = _get_mock_web_results(state["topic"])
        else:
            print("[Web Search Fallback Node] Tavily key missing. Using mock data.")
            web_results = _get_mock_web_results(state["topic"])
        return {"web_search_results": web_results}

    def _synthesis_node(state: ResearchState) -> Dict[str, Any]:
        topic = state["topic"]
        docs = state.get("retrieved_docs", [])
        web_results = state.get("web_search_results", [])
        print(f"\n[Synthesis Agent Node] Compiling final report for: '{topic}'...")
        doc_context_str = ""
        if docs:
            for i, doc in enumerate(docs, 1):
                source = doc.metadata.get("source", "Supabase Vector Store")
                doc_context_str += f"\n--- Vector Document [{i}] (Source: {source}) ---\n{doc.page_content}\n"
        else:
            doc_context_str = "No dense vector documents were retrieved."
        web_context_str = ""
        if web_results:
            for i, res in enumerate(web_results, 1):
                title = res.get("title", "Web Result")
                url = res.get("url", "#")
                snippet = res.get("snippet", res.get("content", ""))
                web_context_str += f"\n--- Web Search Result [{i}] ---\nTitle: {title}\nURL: {url}\nSnippet: {snippet}\n"
        else:
            web_context_str = "No web search fallback context was required."
        llm = get_groq_llm(groq_api_key=_groq_key, temperature=0.2)
        if llm:
            try:
                synthesis_prompt = ChatPromptTemplate.from_messages([
                    ("system", """You are a Lead AI Systems Engineer writing an executive technical report.
Synthesize the provided vector database context and web search context into a highly structured, polished Markdown report.

Required Sections:
# Executive Summary
## Key Technical Insights
## Comparative Analysis & Findings
## Source Citations

Ensure tone is professional, technical, authoritative, and concise."""),
                    ("human", """Research Topic: {topic}

=== SUPABASE VECTOR DATABASE CONTEXT ===
{vector_context}

=== WEB SEARCH FALLBACK CONTEXT ===
{web_context}
""")
                ])
                messages = synthesis_prompt.format_messages(
                    topic=topic,
                    vector_context=doc_context_str,
                    web_context=web_context_str
                )
                response = llm.invoke(messages)
                report_content = response.content
            except Exception as e:
                print(f"[Synthesis Agent Node] Groq LLM synthesis failed ({e}). Generating template report.")
                report_content = _generate_fallback_report(topic, doc_context_str, web_context_str)
        else:
            print("[Synthesis Agent Node] No Groq API Key. Generating offline report.")
            report_content = _generate_fallback_report(topic, doc_context_str, web_context_str)
        print("[Synthesis Agent Node] Report synthesized successfully.")
        return {"final_report": report_content}

    # ── Build & compile the graph ──────────────────────────────────────────────
    builder = StateGraph(ResearchState)
    builder.add_node("orchestrator", _orchestrator_node)
    builder.add_node("retriever",    _retrieval_node)
    builder.add_node("web_search",   _web_search_node)
    builder.add_node("synthesis",    _synthesis_node)

    builder.add_edge(START, "orchestrator")
    builder.add_edge("orchestrator", "retriever")
    builder.add_conditional_edges(
        "retriever",
        decide_fallback,
        {"web_search": "web_search", "synthesis": "synthesis"}
    )
    builder.add_edge("web_search", "synthesis")
    builder.add_edge("synthesis", END)

    graph = builder.compile()
    return graph


# ============================================================================
# 8. EXECUTABLE ENTRY POINT
# ============================================================================
if __name__ == "__main__":
    print("=" * 70)
    print("      MULTI-AGENT DOCUMENT RESEARCH & ANALYTICS SYSTEM")
    print("               (LangGraph + Supabase RAG + ChatGroq)")
    print("=" * 70)

    # Sample input research topic
    sample_topic = "High-Performance RAG Architecture with Supabase pgvector and LangGraph"

    # Initial Graph State
    initial_state: ResearchState = {
        "topic": sample_topic,
        "search_queries": [],
        "retrieved_docs": [],
        "web_search_results": [],
        "need_web_search": False,
        "final_report": ""
    }

    # Compile and invoke workflow graph
    research_graph = build_research_graph()
    print(f"\n[Main] Invoking workflow graph for topic: '{sample_topic}'...")
    
    final_output_state = research_graph.invoke(initial_state)

    print("\n" + "=" * 70)
    print("                    FINAL SYNTHESIZED REPORT")
    print("=" * 70 + "\n")
    print(final_output_state["final_report"])
    print("\n" + "=" * 70)
    print("[Main] Execution completed successfully.")
